- src/main/java/com/jobmoa/app/biz/main/MainDTO.java
- src/main/resources/applicationContext.xml
> [DB 연결] JOBMOA Project DB Connect

- src/main/java/com/jobmoa/app/view/participant/ParticipantController.java
- src/main/webapp/WEB-INF/tags/gnb.tag
- src/main/webapp/WEB-INF/views/DashBoardPage.jsp
- src/main/webapp/WEB-INF/views/NewParticipantsPage.jsp
- src/main/webapp/css/datepicker.css
- src/main/webapp/js/dashBoardJS.js
- src/main/webapp/js/datepickerJS.js
- src/main/webapp/js/drawChartCenterTextPlugin.js
- src/main/webapp/js/recommendJS.js
(주)잡모아 프로젝트
참여자 입력을 위한 입력 폼 제작완료
datePicker 사용 날짜 입력 폼제작
추천 목록을 띄워 사용자 편의성 추가
> [코드 수정 및 페이지 추가] 사용자 입력 폼 제작

- pom.xml
- src/main/java/com/jobmoa/app/biz/particcertif/ParticcertifDAO.java
- src/main/java/com/jobmoa/app/biz/particcertif/ParticcertifService.java
- src/main/java/com/jobmoa/app/biz/participantBasic/BasicDAO.java
- src/main/java/com/jobmoa/app/biz/participantBasic/BasicService.java
- src/main/java/com/jobmoa/app/biz/participantCounsel/CounselDAO.java
- src/main/java/com/jobmoa/app/biz/participantCounsel/CounselDTO.java
- src/main/java/com/jobmoa/app/biz/participantCounsel/CounselService.java
- src/main/java/com/jobmoa/app/biz/participantEmployment/EmploymentDAO.java
- src/main/java/com/jobmoa/app/biz/participantEmployment/EmploymentDTO.java
- src/main/java/com/jobmoa/app/biz/participantEmployment/EmploymentService.java
- src/main/java/com/jobmoa/app/view/participant/ParticipantController.java
- src/main/resources/mappings/Basic-mapping.xml
- src/main/resources/mappings/Counsel-mapping.xml
- src/main/resources/mappings/Employment-mapping.xml
- src/main/resources/mappings/Particcertif-mapping.xml
- src/main/resources/sql-map-config.xml
- src/main/webapp/WEB-INF/ds-servlet.xml
- src/main/webapp/WEB-INF/views/DashBoardPage.jsp
- src/main/webapp/WEB-INF/views/NewParticipantsPage.jsp
- src/main/webapp/WEB-INF/views/participantMain.jsp
참여자 등록 페이지 기능 제작 완료
오류 해결 및 기능 추가 완료
> [코드 수정] 참여자 등록 페이지 기능 제작

- src/main/webapp/WEB-INF/views/UpdateBasicPage.jsp
- src/main/webapp/WEB-INF/views/UpdateCounselPage.jsp
- src/main/webapp/WEB-INF/views/UpdateEmploymentPage.jsp
- src/main/webapp/WEB-INF/views/participantMain.jsp
- src/main/webapp/js/particcertifDiv.js
UpdateBasicPage.jsp
UpdateCounselPage.jsp
UpdateEmploymentPage.jsp
연결될 수정페이지
> [코드 수정] 참여자 수정 버튼 추가

- src/main/java/com/jobmoa/app/biz/particcertif/ParticcertifDAO.java
- src/main/java/com/jobmoa/app/biz/particcertif/ParticcertifDTO.java
- src/main/java/com/jobmoa/app/biz/particcertif/ParticcertifService.java
- src/main/java/com/jobmoa/app/biz/participantBasic/BasicDAO.java
- src/main/java/com/jobmoa/app/biz/participantBasic/BasicService.java
- src/main/java/com/jobmoa/app/biz/participantCounsel/CounselDAO.java
- src/main/java/com/jobmoa/app/biz/participantCounsel/CounselDTO.java
- src/main/java/com/jobmoa/app/biz/participantCounsel/CounselService.java
- src/main/java/com/jobmoa/app/biz/participantEmployment/EmploymentDAO.java
- src/main/java/com/jobmoa/app/biz/participantEmployment/EmploymentService.java
- src/main/java/com/jobmoa/app/view/participant/ParticipantController.java
- src/main/java/com/jobmoa/app/view/participant/UpdateController.java
- src/main/resources/applicationContext.xml
- src/main/resources/mappings/Basic-mapping.xml
- src/main/resources/mappings/Counsel-mapping.xml
- src/main/resources/mappings/Employment-mapping.xml
- src/main/resources/mappings/Particcertif-mapping.xml
- src/main/resources/mappings/Participant-mapping.xml
- src/main/webapp/WEB-INF/tags/gnb.tag
- src/main/webapp/WEB-INF/views/NewParticipantsPage.jsp
- src/main/webapp/WEB-INF/views/UpdateBasicPage.jsp
- src/main/webapp/WEB-INF/views/UpdateCounselPage.jsp
- src/main/webapp/WEB-INF/views/UpdateEmploymentPage.jsp
- src/main/webapp/js/particcertifDiv.js
- src/main/webapp/js/selectOptionJS.js
UpdateBasicPage.jsp
UpdateCounselPage.jsp
UpdateEmploymentPage.jsp
연결될 수정페이지 완료
백단 작업 완료
Error 확인 전 작업 내용
> [페이지 제작] 참여자 수정 페이지 완료

- src/main/java/com/jobmoa/app/biz/participantCounsel/CounselDAO.java
- src/main/java/com/jobmoa/app/biz/participantCounsel/CounselService.java
- src/main/java/com/jobmoa/app/view/participant/UpdateController.java
- src/main/resources/applicationContext.xml
- src/main/resources/mappings/Basic-mapping.xml
- src/main/resources/mappings/Counsel-mapping.xml
- src/main/resources/mappings/Employment-mapping.xml
- src/main/resources/mappings/Member-mapping.xml
- src/main/resources/mappings/Particcertif-mapping.xml
- src/main/resources/mappings/Participant-mapping.xml
- src/main/webapp/WEB-INF/views/NewParticipantsPage.jsp
- src/main/webapp/WEB-INF/views/UpdateEmploymentPage.jsp
- src/main/webapp/js/selectOptionJS.js
진행 유형이 미고보, 고보일반, 등으로 변경되면
그에 맞는 유형으로 변경하는 JS 추가
백단
update 문 수정
Controller 수정
> [JS 수정] 진행 유형 별 취업 유형 변경 JS 수정

- src/main/java/com/jobmoa/app/biz/participant/ParticipantDTO.java
- src/main/java/com/jobmoa/app/biz/participantBasic/BasicDTO.java
- src/main/java/com/jobmoa/app/biz/participantBasic/BasicServiceImpl.java
- src/main/java/com/jobmoa/app/biz/participantCounsel/CounselDTO.java
- src/main/java/com/jobmoa/app/biz/participantEmployment/EmploymentDTO.java
- src/main/java/com/jobmoa/app/view/function/InfoBean.java
- src/main/java/com/jobmoa/app/view/participant/ParticipantController.java
- src/main/java/com/jobmoa/app/view/participant/UpdateController.java
- src/main/resources/mappings/Basic-mapping.xml
- src/main/resources/mappings/Counsel-mapping.xml
- src/main/resources/mappings/Education-mapping.xml
- src/main/resources/mappings/Employment-mapping.xml
- src/main/resources/mappings/Member-mapping.xml
- src/main/resources/mappings/Particcertif-mapping.xml
- src/main/resources/mappings/Participant-mapping.xml
- src/main/webapp/WEB-INF/tags/ParticipantBasic.tag
- src/main/webapp/WEB-INF/tags/ParticipantCounsel.tag
- src/main/webapp/WEB-INF/tags/ParticipantEmployment.tag
- src/main/webapp/WEB-INF/views/NewParticipantsPage.jsp
- src/main/webapp/WEB-INF/views/UpdateCounselPage.jsp
- src/main/webapp/WEB-INF/views/UpdateEmploymentPage.jsp
- src/main/webapp/WEB-INF/views/UpdateParticipantsPage.jsp
- src/main/webapp/WEB-INF/views/info.jsp
- src/main/webapp/js/educationDiv.js
- src/main/webapp/js/particcertifDiv.js
tag 추가하여 중복 코드 제거
클라이언트 요청으로 update page 통합 작업 진행중
작업 내역 중간 저장 사항
> [코드 수정] 요청으로 update page 통합

- src/main/java/com/jobmoa/app/biz/dashboard/DashboardDTO.java
- src/main/java/com/jobmoa/app/biz/participant/ParticipantDAO.java
- src/main/java/com/jobmoa/app/biz/participant/ParticipantDTO.java
- src/main/java/com/jobmoa/app/biz/participant/ParticipantServiceImpl.java
- src/main/java/com/jobmoa/app/biz/participantBasic/BasicDTO.java
- src/main/java/com/jobmoa/app/view/dashboard/DashboardMainController.java
- src/main/java/com/jobmoa/app/view/management/ParticipantManagement.java
- src/main/resources/mappings/Basic-mapping.xml
- src/main/resources/mappings/Dashboard-mapping.xml
- src/main/resources/mappings/Employment-mapping.xml
- src/main/resources/mappings/Participant-mapping.xml
- src/main/webapp/WEB-INF/ds-servlet.xml
- src/main/webapp/WEB-INF/external/participant_management_page.jsp
- src/main/webapp/WEB-INF/tags/ParticipantBasic.tag
- src/main/webapp/WEB-INF/tags/ParticipantCounsel.tag
- src/main/webapp/WEB-INF/views/DashBoardPage.jsp
- src/main/webapp/WEB-INF/views/UpdateCounselPage.jsp
- src/main/webapp/WEB-INF/views/UpdateEmploymentPage.jsp
- src/main/webapp/WEB-INF/views/UpdateParticipantsPage.jsp
- src/main/webapp/WEB-INF/views/participantMain.jsp
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/css/dashboard.css
- src/main/webapp/js/InputLimits.js
- UpdateEmploymentPage.jsp
- 참여자 취업정보 수정 관련 GNB 서브헤더 변경
- 취창업/임금/취업인센티브 필수 입력값 검증 및 알림 로직 추가
- selectOption 및 changeSelect 호출 순서 조정
- UpdateCounselPage.jsp
- 참여자 상담정보 수정 관련 GNB 서브헤더 변경
- ParticipantServiceImpl.java
- `log.info` 주석 처리로 불필요한 로그 출력 제거
- DashboardDTO.java
- Dashboard 업무 현황 관련 변수 추가 (`dashBoardCloseCount`, `dashBoardLastCons`, `dashBoardJobEX`, `dashBoardEXPDate`)
- Dashboard-mapping.xml
- ISNULL 방식으로 NULL 처리 도입 및 IIF 구문으로 SQL 조건식 개선
- Dashboard 쿼리 수정 및 신규 쿼리 추가
- 금일 업무 현황, 마감 참여자 인원, 15일 도래 상담·구직·기간 만료 데이터 조회
- ds-servlet.xml
- `com.jobmoa.app.view.management` 경로 추가
- web.xml
- `<url-pattern>` 수정 추가 작업
> [Page Add] 외부 기업 참여자 조회 페이지 제작

- src/main/java/com/jobmoa/app/biz/dashboard/DashboardDAO.java
- src/main/java/com/jobmoa/app/biz/dashboard/DashboardDTO.java
- src/main/java/com/jobmoa/app/biz/dashboard/DashboardServiceImpl.java
- src/main/java/com/jobmoa/app/biz/login/MemberDAO.java
- src/main/java/com/jobmoa/app/biz/particcertif/ParticcertifDAO.java
- src/main/java/com/jobmoa/app/biz/particcertif/ParticcertifServiceImpl.java
- src/main/java/com/jobmoa/app/biz/participant/ParticipantDAO.java
- src/main/java/com/jobmoa/app/biz/participantBasic/BasicDAO.java
- src/main/java/com/jobmoa/app/biz/participantBasic/BasicServiceImpl.java
- src/main/java/com/jobmoa/app/biz/participantCounsel/CounselServiceImpl.java
- src/main/java/com/jobmoa/app/biz/participantEducation/EducationDAO.java
- src/main/java/com/jobmoa/app/biz/participantEducation/EducationServiceImpl.java
- src/main/java/com/jobmoa/app/biz/participantEmployment/EmploymentDAO.java
- src/main/java/com/jobmoa/app/biz/participantEmployment/EmploymentServiceImpl.java
- src/main/java/com/jobmoa/app/view/dashboard/DashboardMainController.java
- src/main/java/com/jobmoa/app/view/management/ParticipantManagement.java
- src/main/java/com/jobmoa/app/view/participant/ParticipantController.java
- src/main/java/com/jobmoa/app/view/participant/UpdateController.java
- src/main/resources/mappings/Dashboard-mapping.xml
- src/main/webapp/WEB-INF/external/participant_management_page.jsp
- src/main/webapp/WEB-INF/tags/gnb.tag
- src/main/webapp/WEB-INF/views/DashBoardPage.jsp
- src/main/webapp/WEB-INF/views/NewParticipantsPage.jsp
- src/main/webapp/WEB-INF/views/info.jsp
- src/main/webapp/WEB-INF/views/login.jsp
- src/main/webapp/js/datepickerJS.js
- DashboardDTO에 새로운 필드 dashBoardInItCons 추가 및 해당 필드 관련 데이터 조회 로직 추가
- `DashboardServiceImpl`, `DashboardDAO`, `DashboardMapping.xml`에서 로그 수정 및 기능 개선
- 날짜 입력 검증 로직 강화(dashboardJS.js) 및 입력 형식 지정 기능 추가
- 메타 태그 추가로 웹 페이지(view, tag) 반응형 디자인 개선
- gnb.tag 및 외부 기업 제공용 페이지에서 UI 요소 간격 조정 및 알림 기능 추가
- 데이터 접근 객체(DAO) 및 관련 서비스(ServiceImpl) 내 불필요한 상세 로그 제거 및 로깅 메커니즘 개선
> [코드 수정] 정리 및 로그 수정 로직 강화

- src/main/java/com/jobmoa/app/view/chatBot/ChatBotFunction.java
- src/main/java/com/jobmoa/app/view/chatBot/ChatBotService.java
- src/main/java/com/jobmoa/app/view/chatBot/ChatController.java
- src/main/java/com/jobmoa/app/view/chatBot/ChatRequest.java
- src/main/java/com/jobmoa/app/view/chatBot/chatAjax.java
- src/main/webapp/WEB-INF/chatBot/ChatBot.jsp
- src/main/webapp/WEB-INF/tags/footer.tag
- src/main/webapp/css/chatBot.css
- src/main/webapp/css/footerCss.css
- src/main/webapp/js/chatBotAsync.js
- src/main/webapp/js/footerJS.js
- ChatBot의 대화 쓰레드 생성 기능 추가 (createThread 메서드)
- ChatBot 서비스 로직을 분리하여 ChatBotFunction 클래스 추가
- ChatRequest 클래스에 threadId 및 assistantsId 필드 추가
- ChatBot.jsp에 threadId와 assistantsId 히든 필드 추가 및 초기화 스크립트 작성
- chatBotAsync.js에 threadId 및 assistantsId 처리 로직 추가
- ChatBotService에서 대화 구조 및 API 호출 로직 개선 (K-STAR-K 자기소개서 구조 추가)
- CSS 수정으로 UI 크기 조정 (채팅 입력 및 출력 영역 등 크기 변경)
- footerJS.js에서 이벤트 리스너 메서드 오류 수정 (.add → .on)
- footer.tag에서 챗봇 버튼 위치 조정 및 관련 CSS 수정
API 호출 및 화면 상호작용 간의 로직을 분리하고 유지보수성을 높이기 위한 구조적 개선을 진행하였음.
> ChatBot 기능 확장 및 UI/UX 개선

- src/main/java/com/jobmoa/app/view/chatBot/ChatBotFunction.java
- src/main/java/com/jobmoa/app/view/chatBot/ChatBotService.java
- src/main/java/com/jobmoa/app/view/chatBot/ChatController.java
- src/main/java/com/jobmoa/app/view/chatBot/ChatRequest.java
- src/main/java/com/jobmoa/app/view/chatBot/chatAjax.java
- src/main/resources/applicationContext.xml
- src/main/webapp/WEB-INF/tags/ParticipantBasic.tag
- src/main/webapp/js/chatBotAsync.js
- src/main/webapp/sql/CreateSQL.sql
- ChatController에서 chatBotRequestJson 메서드 매개변수 확장 (isPost 추가)
- ChatAjax에서 ChatGPT 요청 처리 로직 간소화 및 예외 처리 방식 변경
- ChatRequest에 runId 필드 추가
- ChatBotFunction에서 POST/GET 메서드 구별 로직 추가 (isRequestPost)
- ChatBotService에서 메시지 생성, Run 생성 및 조회 구현으로 ChatGPT 호출 과정 리팩토링
- ChatBotAsync.js 비동기 처리 방식 수정 및 DOM 업데이트 로직 개선
- ParticipantBasic 태그에서 select 박스 옵션 수정
- applicationContext.xml 설정 파일 보안 강화를 위해 Database 정보 비워둠
- 신규 SQL 테이블 및 VIEW 생성 (참여자 관리 및 이력 데이터 처리)
- SUCCESSMONEY 및 EXTERNALPARTICIPANT 뷰 정의 추가 및 성공금 계산 로직 포함
- 사용자 기본 이메일 자동 생성 트리거 추가 (trg_SetEmail)
보안 및 신규 기능 추가에 중점 둔 개선 작업 적용.
> ChatBot 기능 개선 및 SQL 구조 추가

- src/main/java/com/jobmoa/app/biz/participant/ParticipantDTO.java
- src/main/java/com/jobmoa/app/biz/participant/ParticipantServiceImpl.java
- src/main/java/com/jobmoa/app/view/management/ParticipantManagement.java
- src/main/java/com/jobmoa/app/view/participant/ParticipantController.java
- src/main/java/com/jobmoa/app/view/report/DailyWorkReport.java
- src/main/java/com/jobmoa/app/view/report/DailyWorkReport2.java
- src/main/java/com/jobmoa/app/view/report/DailyWorkReport3.java
- src/main/resources/mappings/Participant-mapping.xml
- src/main/webapp/WEB-INF/external/participant_management_page.jsp
- src/main/webapp/WEB-INF/tags/gnb.tag
- src/main/webapp/WEB-INF/views/participantMain.jsp
참여자 검색 및 필터 업데이트, UI 개선 및 검색 로직 최적화
- 검색 폼에 새로운 hidden input 추가 및 필터링 옵션 확장 (학교명 및 상태 필터 추가)
- 검색 버튼에 아이콘 추가로 UI 개선
- 검색 결과가 없을 시 메시지 변경 ("신규 참여자를 등록해주세요" → "검색된 참여자가 없습니다.")
- 검색 폼을 GET 방식의 submit 형태로 변경하여 검색 로직 개선
- 배정 현황 및 알선취업 성과 현황 등의 Excel 리포트 작성에 필요한 구조 및 병합/테두리 설정 추가
- ParticipantController와 ParticipantDTO에 searchType 처리 로직 추가
- Participant-mapping.xml에 조건 검색 쿼리 추가 및 수정
- 외부 경로 URL 수정 ("./index.jsp" → "/external/jobseekers") 및 레이블/항목 텍스트 가독성 향상 ("희망연봉" → "희망연봉/월급")
```
> 참여자 검색 및 필터 업데이트, UI 개선 및 검색 로직 최적화

- src/main/java/com/jobmoa/app/biz/participant/ParticipantDTO.java
- src/main/java/com/jobmoa/app/biz/participantCounsel/CounselDTO.java
- src/main/java/com/jobmoa/app/biz/report/ReportDAO.java
- src/main/java/com/jobmoa/app/biz/report/ReportDTO.java
- src/main/java/com/jobmoa/app/biz/report/ReportService.java
- src/main/java/com/jobmoa/app/biz/report/ReportServiceImpl.java
- src/main/java/com/jobmoa/app/view/participant/ParticipantController.java
- src/main/resources/mappings/Counsel-mapping.xml
- src/main/resources/mappings/Dashboard-mapping.xml
- src/main/webapp/WEB-INF/tags/ParticipantCounsel.tag
- src/main/webapp/WEB-INF/tags/gnb.tag
- src/main/webapp/WEB-INF/views/NewParticipantsPage.jsp
- src/main/webapp/WEB-INF/views/UpdateCounselPage.jsp
- src/main/webapp/WEB-INF/views/participantMain.jsp
- src/main/webapp/js/datepickerJS.js
- JSP 페이지 수정: `pageRows` 옵션 수정과 진행단계 유효성 검증 추가
- ParticipantController 페이지 기본값 변경: `pageRows` 초기값 10 → 100 수정
- Counsel-mapping.xml 및 관련 DTO 수정: `중단종료일(counselEndDate)` 속성 추가
- 진행단계별 중단종료일 필수 입력 로직 추가
- Report 기능 구현:
- 신규 DTO(ReportDTO), DAO, ServiceImpl, Service 추가
- ReportDAO 및 Service를 통해 기본 CRUD 메소드 구현
- 기존 gnb.nav 태그에서 미사용 기능 활성화 및 주석 제거
- datepicker 설정 수정: 특정 요일 비활성화 코드 주석 처리
- 레거시 코드 개선 및 불필요한 코드 제거
> 페이징 및 진행단계 로직 수정, 신규 Report 기능 추가 구현

- src/main/java/com/jobmoa/app/biz/login/MemberDAO.java
- src/main/java/com/jobmoa/app/biz/participant/ParticipantDTO.java
- src/main/java/com/jobmoa/app/biz/report/ReportDAO.java
- src/main/java/com/jobmoa/app/biz/report/ReportDTO.java
- src/main/java/com/jobmoa/app/biz/report/ReportService.java
- src/main/java/com/jobmoa/app/biz/report/ReportServiceImpl.java
- src/main/java/com/jobmoa/app/view/report/DailyWorkReport3.java
- src/main/resources/mappings/Dashboard-mapping.xml
- src/main/resources/mappings/Member-mapping.xml
- src/main/resources/mappings/Participant-mapping.xml
- src/main/resources/mappings/Report-mapping.xml
- src/main/resources/sql-map-config.xml
- src/main/webapp/WEB-INF/tags/DailyWorkReport.tag
- src/main/webapp/WEB-INF/views/DailyWorkReportPage.jsp
- src/main/webapp/WEB-INF/views/participantMain.jsp
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/css/dailyWorkReportCss.css
* DailyWorkReport 기능 삭제 및 관련 Tag 파일 제거
- src/main/webapp/WEB-INF/tags/DailyWorkReport.tag 파일 삭제
* `participantMain.jsp`에 상담도래일 컬럼 추가 및 필터 기능 구현
- 최근 상담일 기준으로 조건별 색상 구분 로직 추가
* `MemberDAO` 및 `Member-mapping.xml` 수정
- 회원 검색 조건 및 데이터 처리 로직 개선
* `Dashboard-mapping.xml` 로직 변경
- 일부 쿼리 수정 및 지점 필터링 조건 추가
* `Participant-mapping.xml` 데이터 필드 확장
- 상담도래자(participantAdventCons) 필드 추가 및 계산 로직 반영
* `dailyWorkReportCss.css` 신규 추가
- Excel 다운로드 버튼과 Drag & Drop UI 스타일 정의
* `DailyWorkReport3.java` 코드 리팩토링 및 기능 추가
- 보고서 생성, 배정 인원, 참여자 진행현황 데이터 처리 로직 추가
* 세션 타임아웃 360분 설정
> DailyWorkReport.tag 삭제, 참여자 관리 및 보고서 기능 개선

- src/main/java/com/jobmoa/app/biz/bean/SearchBean.java
- src/main/java/com/jobmoa/app/biz/participant/ParticipantDAO.java
- src/main/java/com/jobmoa/app/biz/participant/ParticipantDTO.java
- src/main/java/com/jobmoa/app/biz/participantCounsel/CounselDTO.java
- src/main/java/com/jobmoa/app/biz/participantEmployment/EmploymentDTO.java
- src/main/java/com/jobmoa/app/view/dashboard/DashboardMainController.java
- src/main/java/com/jobmoa/app/view/participant/UpdateController.java
- src/main/java/com/jobmoa/app/view/report/DailyWorkReport3.java
- src/main/java/com/jobmoa/app/view/report/ParticipantAllExcel.java
- src/main/resources/mappings/Participant-mapping.xml
- src/main/webapp/WEB-INF/tags/ParticipantCounsel.tag
- src/main/webapp/WEB-INF/views/DashBoardPage.jsp
- src/main/webapp/WEB-INF/views/NewParticipantsPage.jsp
- src/main/webapp/WEB-INF/views/UpdateBasicPage.jsp
- src/main/webapp/WEB-INF/views/UpdateCounselPage.jsp
- src/main/webapp/WEB-INF/views/UpdateEmploymentPage.jsp
- src/main/webapp/WEB-INF/views/UpdateParticipantsPage.jsp
- src/main/webapp/WEB-INF/views/participantMain.jsp
- 조회 페이지에 엑셀 다운로드 버튼 추가 및 관련 CSS 적용
- 테이블 컬럼에 오름차순/내림차순 정렬 기능 구현
- 검색 기능에 연도 필터 추가
- 참여자 정보 업데이트 및 반환 링크에 SearchBean을 사용하여 파라미터 관리 개선
- `InfoBean` 제거 및 관련 URL 구성 간소화
- 기존 URL 파라미터 처리 로직 개선 및 정리
- 참여자의 상태(마감/진행중) 변경 기능 개선
- 최근 상담일에 따른 색상 필터 로직 수정
- 다중 반환 링크 및 URL 조합 코드 리팩토링
> 참여자 조회 및 업데이트 기능 개선

- src/main/java/com/jobmoa/app/biz/bean/LoginBean.java
- src/main/java/com/jobmoa/app/biz/bean/SearchBean.java
- src/main/resources/mappings/Counsel-mapping.xml
- src/main/resources/mappings/Employment-mapping.xml
- src/main/webapp/WEB-INF/tags/searchHiddenInput.tag
- src/main/webapp/WEB-INF/views/UpdateBasicPage.jsp
- src/main/webapp/WEB-INF/views/UpdateCounselPage.jsp
- src/main/webapp/WEB-INF/views/UpdateEmploymentPage.jsp
- src/main/webapp/WEB-INF/views/UpdateParticipantsPage.jsp
- Counsel-mapping.xml, Employment-mapping.xml: 참여자 데이터 항목(counselPartic, employmentPartic) 추가
- SearchBean.java: participantRegDate 필드 추가 및 toString 로직 수정
- UpdateParticipantsPage.jsp, UpdateCounselPage.jsp, UpdateBasicPage.jsp, UpdateEmploymentPage.jsp:
- gnb 서브헤더에 참여자 동적 데이터 표시
- 검색 필터 hiddenInput 태그(searchHiddenInput.tag) 참조로 대체
- searchHiddenInput.tag: 검색 관련 input 태그 공통화 위해 새 파일 생성
- JSP Alert 메시지 문구 오탈자 수정("중단종료일" -> "진행종료일")
> 참여자 및 상담 데이터 구조 및 UI 개선

- src/main/java/com/jobmoa/app/view/report/DailyWorkReport3.java
- src/main/java/com/jobmoa/app/view/report/ParticipantAllExcel.java
- src/main/webapp/WEB-INF/views/login.jsp
- login.jsp 파일 전면 수정:
- 부트스트랩 5 도입으로 디자인 및 반응형 레이아웃 적용
- 비밀번호 찾기 기능 모달 창 추가
- jQuery 및 에니메이션 효과 추가로 UX 향상
- ParticipantAllExcel 클래스:
- 템플릿 캐시 변수명을 templateBytes2로 변경
- 관련 로직 변수명 동기화 및 로그 메시지 수정
- DailyWorkReport3 클래스:
- 민간위탁기관 평가 실적 섹션의 제목 위치 셀 변경
> 로그인 페이지 UI 개선 및 기능 추가

- src/main/java/com/jobmoa/app/biz/bean/SearchBean.java
- src/main/resources/mappings/Participant-mapping.xml
- src/main/resources/mappings/Report-mapping.xml
- src/main/webapp/WEB-INF/views/DailyWorkReportPage.jsp
- src/main/webapp/WEB-INF/views/participantMain.jsp
- src/main/webapp/js/sweetAlert.js
- `participantMain.jsp`:
- 선택된 참여자 이름 불러오는 `getParticipantName` 함수 추가.
- 삭제/마감 버튼 클릭 시 확인창(SweetAlert)과 연동하여 사용자 확인 로직 추가.
- 삭제 요청 로직 및 마감 상태 변경 로직 개선.
- `SearchBean.java`:
- `toString` 메서드에서 null 및 빈값 체크 로직 개선.
- 기본값 설정 변경(`endDateOption`, `searchOption` 등).
- `Report-mapping.xml`:
- 취소 상태의 참여자를 제외시키는 조건 추가.
- `Participant-mapping.xml`:
- `ORDER BY` 관련 불필요한 조건 제거로 효율성 개선.
- `DailyWorkReportPage.jsp`:
- 금일/금주/금월/금년 누적 실적 및 금일 배정 인원 UI 추가.
- 전담자 목록 상의 드래그 핸들 및 체크박스 UI 개선.
- `sweetAlert.js`:
- SweetAlert에서 버튼 순서 설정 변경(`reverseButtons: false`).
기능 및 UI 전반적인 개선을 통해 사용자 경험 향상 및 코드 가독성 개선.
> 선택 기능 및 UI/로직 개선 업데이트

- src/main/java/com/jobmoa/app/biz/bean/SearchBean.java
- src/main/java/com/jobmoa/app/biz/dashboard/DashboardDAO.java
- src/main/java/com/jobmoa/app/biz/dashboard/DashboardDTO.java
- src/main/java/com/jobmoa/app/biz/login/MemberDAO.java
- src/main/java/com/jobmoa/app/biz/login/MemberDTO.java
- src/main/java/com/jobmoa/app/biz/report/ReportDTO.java
- src/main/java/com/jobmoa/app/view/chatBot/ChatBotController.java
- src/main/java/com/jobmoa/app/view/dashboard/DashboardMainController.java
- src/main/java/com/jobmoa/app/view/function/ChangeJson.java
- src/main/java/com/jobmoa/app/view/login/LoginController.java
- src/main/java/com/jobmoa/app/view/participant/ParticipantController.java
- src/main/java/com/jobmoa/app/view/report/DailyWorkReport3.java
- src/main/java/com/jobmoa/app/view/report/ParticipantAllExcel.java
- src/main/resources/applicationContext.xml
- src/main/resources/mappings/Dashboard-mapping.xml
- src/main/resources/mappings/Member-mapping.xml
- src/main/resources/mappings/Report-mapping.xml
- src/main/webapp/Deamo.jsp
- src/main/webapp/WEB-INF/tags/gnb.tag
- src/main/webapp/WEB-INF/views/DailyWorkReportPage.jsp
- src/main/webapp/WEB-INF/views/DashBoardPage.jsp
- src/main/webapp/WEB-INF/views/DashBoardSuccessMoneyPage.jsp
- src/main/webapp/WEB-INF/views/participantMain.jsp
- src/main/webapp/css/dailyWorkReportCss.css
- src/main/webapp/js/InputLimits.js
- 참여자 메인 화면 UI 개선:
- '현재 화면 참여자' 및 '검색된 참여자 수' 표시 추가
- select 옵션 값 all → allType으로 변경 및 관련 로직 수정
- ChatBotController:
- 현재 시간 반환 로직 간소화 (toString() 제거)
- MemberDAO:
- 미사용 log 주석 처리
- update 기능 로직 추가 및 log 보완
- ParticipantController:
- 마감 여부 기본값 지정 로직 추가
- 검색된 참여자 수 변수 모델에 추가
- SQL 매핑:
- 새로운 Update 및 Select 쿼리 추가
- 로그인 정보 테이블에 디테일 필드 확장
- 기타:
- 성공금 관련 신규 JSP (DashBoardSuccessMoneyPage.jsp) 추가
- Excel 다운로드 파일명 인코딩 처리 방식 수정 (StandardCharsets.UTF_8 적용)
- ApexCharts를 이용한 데이터 시각화 구현 추가
> [수정 사항] 기능, 페이지 추가 및 오류 사항 추가

- src/main/java/com/jobmoa/app/view/branchManagement/BranchManagement.java
- src/main/java/com/jobmoa/app/view/dashboard/DashboardMainController.java
- src/main/java/com/jobmoa/app/view/report/ParticipantAllExcel.java
- src/main/resources/mappings/Dashboard-mapping.xml
- src/main/resources/mappings/Participant-mapping.xml
- src/main/webapp/WEB-INF/ds-servlet.xml
- src/main/webapp/WEB-INF/tags/gnb.tag
- src/main/webapp/WEB-INF/views/BranchPariticipant.jsp
- src/main/webapp/WEB-INF/views/DashBoardSuccessMoneyPage.jsp
- 잘못된 태그 제거 및 링크 수정 (/participantExcel.login → /participantExcel.login?condition=participantExcel).
- Dashboard-mapping.xml 수정 및 개선
- 쿼리에서 하드코딩 사용자 ID를 매핑을 통해 파라미터로 변경.
- "전담자_계정" 키의 네이밍 통일 (UserId → UserID).
- 불필요한 공백 제거 및 코드 정리.
- Participant-mapping.xml 확장
- 신규 기능 구현: 지점 및 검색 관련 필터링 쿼리 추가.
- 참여자 전처리 엑셀 데이터 추출 관련 쿼리 보강 및 분리.
- 기본 데이터처리 로직 클린업 및 최적화.
- DashBoardSuccessMoneyPage.jsp 업데이트
- 테이블에 '등록일' 컬럼 추가 및 프론트엔드 개선.
- 차트 렌더링 로직 수정: JSON 데이터 처리 분리 (successMoneyJson, incentiveJson).
- 차트 브러시 기능 추가 등 시각화 개선.
- DashboardMainController.java 개선
- 잘못된 변수명 수정 및 로직 효율화.
- 새 인센티브 데이터(incentiveJson) 처리 추가.
- Null 또는 빈 데이터 조건 처리 로직 추가.
- 기타
- 인포 메시지 추가로 가독성 및 사용자 경험 향상.
> - JSP 파일 participantMain.jsp 코드 개선

- pom.xml
- src/main/java/com/jobmoa/app/biz/participant/ParticipantDAO.java
- src/main/java/com/jobmoa/app/biz/participant/ParticipantDTO.java
- src/main/java/com/jobmoa/app/view/ajaxPackage/ParticipantsTransferAjax.java
- src/main/java/com/jobmoa/app/view/dashboard/DashboardMainController.java
- src/main/java/com/jobmoa/app/view/function/MemberRoleCheck.java
- src/main/java/com/jobmoa/app/view/login/LoginController.java
- src/main/java/com/jobmoa/app/view/management/TransferController.java
- src/main/resources/mappings/Member-mapping.xml
- src/main/resources/mappings/Participant-mapping.xml
- src/main/webapp/WEB-INF/tags/gnb.tag
- src/main/webapp/WEB-INF/views/transferPage.jsp
- **TransferController 추가**: 사용자가 데이터 이전 기능을 사용할 수 있도록 새로운 컨트롤러 추가
- `transfer.login` 핸들러 메서드 구현
- 지점 및 권한 확인 후 특정 상담사에게 데이터 전송 로직 포함
- **타임리프(Thymeleaf) 의존성 추가**: 새로운 JSP 기반 페이지 사용을 위해 `pom.xml`에 타임리프 라이브러리 추가
- **ParticipantDTO 수정**: 데이터 이전을 위한 변수 추가 (`sourceCounselorID`, `targetCounselorID`, `participantIDs` 등)
- **Member-mapping.xml 수정**: 지점 관리자 조회를 위한 쿼리 추가 (`branchUserID`)
- **ParticipantDAO 수정**: 업데이트 로직 개선 및 디버깅 로그 추가
- **페이지 추가**: `transferPage.jsp` 생성, 데이터 이전 UI 포함
- 참여자 체크박스 선택
- 원본 상담사 및 대상 상담사 간의 데이터 이전 UI 설계
- **새로운 유틸 클래스 추가**: `MemberRoleCheck` 생성
- 특정 역할 (총괄, 팀장, 파트장 등)의 유효성 검사를 위한 유틸 클래스
- **Participant-mapping.xml 수정**: 참여자 데이터 이전 동작을 구체화하기 위한 조회 및 갱신 쿼리 추가
- `transferSelect`, `transferUpdate` 쿼리 추가
- **DashboardMainController UI 메시지 변경**: 성공금 데이터와 관련된 알림 메시지 및 아이콘 수정
- …
> 기능 추가 및 코드 개선

- src/main/java/com/jobmoa/app/view/dashboard/DashboardBranchController.java
- src/main/webapp/WEB-INF/tags/ParticipantEmployment.tag
- src/main/webapp/WEB-INF/tags/gnb.tag
- src/main/webapp/WEB-INF/views/DashBoardTotalManagement.jsp
- src/main/webapp/js/dashboard_data_visualization.js
- `DashboardBranchController` 클래스 추가: 지점 대시보드 페이지 매핑용 컨트롤러
- JSP 파일(`DashBoardTotalManagement.jsp`) 생성: 지점별 성공금 및 인센티브 현황 시각화 페이지 구현
- JavaScript 파일(`dashboard_data_visualization.js`) 추가: 지점별 성공금, 인센티브 현황을 위한 ApexCharts 기반 데이터 시각화 기능 구현
- 성공금 현황 그래프, 인센(해당/미해당) 현황, 인센 미해당 비율 시각화 지원
- 지점 선택 시 상담사별 상세 현황 모달 제공
- `ParticipantEmployment.tag` 수정: 인센티브 현황 옵션 "최저임금 미만" 추가
- GNB(`gnb.tag`) 수정: "지점 대시보드" 메뉴 항목 추가
> 지점 대시보드 기능 추가 및 데이터 시각화 지원

- src/main/java/com/jobmoa/app/biz/dashboard/DashboardDTO.java
- src/main/java/com/jobmoa/app/view/dashboard/DashboardBranchController.java
- src/main/resources/mappings/Dashboard-mapping.xml
- src/main/webapp/WEB-INF/tags/ParticipantEmployment.tag
- src/main/webapp/WEB-INF/views/DashBoardTotalManagement.jsp
- src/main/webapp/js/dashboard_data_visualization2.js
- src/main/webapp/js/dashboard_data_visualization3.js
- 인센 현황 시각화를 위한 JS 파일 (`dashboard_data_visualization2.js`, `dashboard_data_visualization3.js`) 추가
- `DashboardBranchController`에서 대시보드 관련 JSON 생성 로직 추가
- 성공 금액, 인센 해당/미해당 현황 데이터 처리
- 기간 기본값 설정 및 JSON 변환 로직 작성
- `DashboardDTO`에 대시보드 관련 필드 추가 (지점별 성공금, 인센 데이터 등)
- 지점 및 인센 현황 데이터 조회를 위한 Dashboard-mapping.xml SQL 쿼리 추가
- 기존 JS 데이터 초기화 방식 리팩토링 (템플릿 데이터를 `initData`로 대체)
- `ParticipantEmployment.tag`에 미해당 분류 옵션 추가 (IAP 7일, 30시간 미만, 기타 등)
- 기존 대시보드 시각화 JS 수정 및 코드 정리
- 기타 코드 포맷 수정 및 리팩토링
> 인센 현황 및 지점 대시보드 기능 추가

- src/main/java/com/jobmoa/app/biz/dashboard/DashboardDTO.java
- src/main/java/com/jobmoa/app/view/ajaxPackage/DashboardAjaxController.java
- src/main/java/com/jobmoa/app/view/dashboard/DashboardBranchController.java
- src/main/resources/mappings/Dashboard-mapping.xml
- src/main/webapp/WEB-INF/views/DashBoardTotalManagement.jsp
- src/main/webapp/js/dashboard_data_visualization.js
- src/main/webapp/js/dashboard_data_visualization2.js
- src/main/webapp/js/dashboard_data_visualization3.js
- 대시보드에서 새로운 데이터 세트 시각화 로직 추가
- Column 유형 차트 적용
- 데이터 색상 및 Y축 레이블 포맷팅 설정
- 새로운 비동기 처리 로직 구현
- Ajax 기반 데이터 동기화 지원
- 지점별 및 조건별 데이터 출력 가능
- 백엔드: 새로운 API 메서드 추가
- `/dashBoardSuccess.login` 및 `/dashBoardInventive.login` API Endpoint 신설
- DashboardDTO와 SQL 매핑 확장, 데이터 필터 추가
- XML 매핑 업데이트
- 인센 미해당 항목 관련 쿼리 개선 및 추가
- 사업부별 데이터 필터 로직 반영
- 프론트엔드:
- JS 코드에서 데이터 전처리 및 동적 라벨링 지원
- 사업부(Business Unit) 및 시작/종료 날짜 기반 데이터 필터 추가
- 스타일 업데이트: 차트의 최저값, 축 정렬 및 색상 개선
=> 개선된 시각화와 더불어 사용자의 데이터 필터링 편의성을 강화함.
> [대시보드 개선 작업]

- src/main/java/com/jobmoa/app/biz/dashboard/DashboardDTO.java
- src/main/java/com/jobmoa/app/view/dashboard/DashboardMainController.java
- src/main/resources/mappings/Dashboard-mapping.xml
- src/main/webapp/WEB-INF/views/DashBoardPage.jsp
- src/main/webapp/WEB-INF/views/DashBoardScoreAndSituation.jsp
- DashboardDTO 클래스에 새로운 통계 필드 추가 (ex. 알선취업자 수, 조기취업자 수, 고용유지자 수 등)
- 새로운 JSP 파일(DashBoardScoreAndSituation.jsp) 추가로 대시보드 점수 및 분포 차트 렌더링 구현
- SQL 쿼리 업데이트를 통해 대시보드의 범용성과 데이터 정확도 개선 (ex. 동적 날짜 변수, 특정 조건 정비)
- 차트 라이브러리(ApexCharts 등) 및 필수 플러그인 적용
> 대시보드 기능 및 데이터 관리 개선

- src/main/java/com/jobmoa/app/view/dashboard/DashboardMainController.java
- src/main/resources/mappings/Dashboard-mapping.xml
- src/main/resources/mappings/Participant-mapping.xml
- src/main/webapp/WEB-INF/views/DashBoardPage.jsp
- src/main/webapp/WEB-INF/views/DashBoardScoreAndSituation.jsp
- 개인 및 전체 점수 데이터를 분리하여 효율적인 계산 구조로 변경.
- 전체 랭킹 및 지점 랭킹 계산 로직 가독성 및 명확성 향상.
- 점수 요약 통계 쿼리 구조 리팩토링.
2. 대시보드 UI 수정
- `distributionChart`에 여백 클래스(`pt-3`) 추가.
- `#success-btn` 링크 URL을 `successMoney.login`으로 수정.
- "다음 등급까지 남은 점수" 계산 로직을 소수점 두 자리로 제한하여 UX 개선.
3. 매핑 파일 개선
- `Participant-mapping.xml`: `participantRegDate` 조건 추가 및 선택형 쿼리 정리.
- `Dashboard-mapping.xml`: `FLOOR` 함수 추가로 임금 조건 비교 정확성 강화.
4. Java 컨트롤러 수정
- 대시보드 성공직업 카운트 로직의 정확성 수정(`getDashBoardBetterJobCountUser`).
5. 디버깅 코드 추가
- `DashBoardPage.jsp` 및 스크립트에서 중요 데이터(`dashBoardSuccessMoney`, 등급 점수 계산) 디버깅 로그 추가.
- 랭크 검증 에러 메시지 수정(‘유효하지 않은 등급입니다.’).
6. 코드 가독성 및 유지보수성 개선
- 불필요한 주석 및 중복 코드 제거.
- SQL 쿼리 및 자바스크립트 데이터 처리 부분에서 명확한 변수 사용.
> 1. 대시보드 점수 및 통계 계산 로직 개선

- src/main/java/com/jobmoa/app/biz/dashboard/DashboardDTO.java
- src/main/java/com/jobmoa/app/view/dashboard/DashboardMainController.java
- src/main/resources/mappings/Dashboard-mapping.xml
- src/main/webapp/WEB-INF/views/DashBoardBranchScoreAndSituation.jsp
- src/main/webapp/WEB-INF/views/DashBoardPage.jsp
- src/main/webapp/js/dashboard_data_visualization3.js
- DashboardDTO 클래스에 새로운 점수 데이터 필드 추가:
* 1인당 점수, 표준 점수, 가중 점수 관련 필드 추가
* 취업률, 알선취업률, 조기취업률, 고용유지율, 나은일자리 등의 세부 점수 필드 추가
- DashBoardScoreAndSituation.jsp
* 점수 차트와 데이터 시각화 개선
* x축 라벨에 세부 점수와 1인당 점수 데이터 반영
* y축 포맷터 추가로 시각적 해상도 개선
* XCategories 변수를 통해 라벨 콘텐츠 정의 및 향상
- dashboard_data_visualization3.js
* 기존 TODO 코멘트를 FIXME로 수정
* 불필요 공백 제거 및 로직 최적화
- Dashboard-mapping.xml
* 대시보드 점수 및 평점 관련 쿼리 개선
* 1인당 점수, 가중 점수, 지점 평균 점수 데이터 출력 추가
* 총점, 평균 점수 데이터를 위한 새로운 쿼리 추가
> 대시보드 점수 및 데이터 계산 로직 및 시각화 개선

- src/main/java/com/jobmoa/app/view/ajaxPackage/DashboardAjaxController.java
- src/main/java/com/jobmoa/app/view/dashboard/DashboardMainController.java
- src/main/java/com/jobmoa/app/view/login/LoginController.java
- src/main/resources/mappings/Dashboard-mapping.xml
- src/main/webapp/WEB-INF/tags/ParticipantCounsel.tag
- src/main/webapp/WEB-INF/views/DashBoardBranchScoreAndSituation.jsp
- 성과 데이터 통계 조회 로직을 수정하여 총점(총평균) 항목 추가 및 기존 점수 집계 로직을 정리
- XML 매핑: SQL 쿼리에 총평균 항목 추가
- Ajax Controller 수정: 관리자 권한과 지점 조건 추가
- DTO 로직 개선: 사용자와 지점 점수 데이터를 유동적으로 처리
- UI 개선 및 데이터 시각화 강화
- JSP 페이지: 로딩 애니메이션 추가 및 구체적 데이터 차트 구성
- JavaScript 변경
* ApexCharts를 활용한 사용자별 점수 및 평균 점수 시각화 추가
* 개별 사용자 ID를 클릭하여 상세 보기로 이동 가능
* 점수 불러오기 시 로딩 상태 표시 및 오류 처리 추가
- 코드 및 조건 정리
- 불필요한 콘솔 로그 제거
- 데이터 초기화 로직 및 함수 역할별 분리
- 관리자 조건 및 비동기 처리 로직 강화
```
> [Dashboard 및 사용자 점수 관리 기능 개선]

- src/main/java/com/jobmoa/app/view/ajaxPackage/DashboardAjaxController.java
- src/main/webapp/WEB-INF/views/DashBoardPage.jsp
- src/main/webapp/WEB-INF/views/DashBoardTotalManagement.jsp
- src/main/webapp/js/dashboard_data_visualization.js
- src/main/webapp/js/dashboard_data_visualization3.js
- src/main/webapp/js/footerJS.js
- footerJS.js 수정:
- 기존 이메일 전송 mailto 링크를 그룹웨어 메일 작성 링크로 변경.
- 불필요한 주석 처리된 코드 정리.
- dashboard_data_visualization3.js 개선:
- 인센티브 데이터 조회 방식 AJAX API 호출로 전환.
- 미해당 인센티브 현황 관련 데이터 처리 로직 추가 및 차트 옵션 개선.
- dashboard_data_visualization.js 개선:
- 상담사 성공금 데이터 조회 AJAX API 호출로 전환.
- 상담사 차트 모달 및 렌더링 기능 강화.
- JSP 파일 수정:
- DashBoardPage.jsp: "상세정보" 버튼 링크 경로를 로그인 사용자 유형에 따라 동적으로 설정.
- DashBoardTotalManagement.jsp: 차트 데이터 로딩 시 사용자 피드백 메시지 영역 추가.
- 레이아웃을 위한 새로운 모달 추가 (서비스 미제공 확인용).
- DashboardAjaxController.java 수정:
- 오류 로그 추가 및 세션 IS_MANAGER 처리 로직 최적화.
추가 개선 및 테스트 예정 사항:
- 일부 주석 처리된 테스트 코드 제거 필요.
- 백엔드 작업 예정 기능 관련 모달 및 로직 추가 (2025-04-21).
> 대시보드 기능 개선 및 버그 수정

- src/main/java/com/jobmoa/app/biz/participant/ParticipantDTO.java
- src/main/java/com/jobmoa/app/view/ajaxPackage/DashboardAjaxController.java
- src/main/java/com/jobmoa/app/view/dashboard/DashboardMainController.java
- src/main/java/com/jobmoa/app/view/login/LoginController.java
- src/main/java/com/jobmoa/app/view/management/TransferController.java
- src/main/resources/mappings/Participant-mapping.xml
- src/main/webapp/WEB-INF/tags/gnb.tag
- src/main/webapp/WEB-INF/views/DashBoardTotalManagement.jsp
- src/main/webapp/js/dashboard_data_visualization3.js
- 대시보드에서 "서비스 미제공" 데이터 조회 및 모달 구현
- "서비스 미제공" 데이터를 조회하는 AJAX 메서드 추가 (noServiceAjax.login)
- ParticipantDTO에 검색 시작 및 종료일 필드 추가
- Participant-mapping.xml에 관련 SQL 쿼리 추가
- 조회 결과를 표시하는 모달과 테이블 UI 구현
- 대시보드 차트 부가기능 추가 및 모달 비우기 규칙 적용
- gnb.tag에 권한 체크 로직 수정 ("BRANCH_MENGER_ROLE" → "IS_BRANCH_MANAGER || IS_MANAGER")
> - 지점 관리자 세션 키 네이밍 수정 ("BRANCH_MENGER_ROLE" → "IS_BRANCH_MANAGER")

- src/main/resources/mappings/Participant-mapping.xml
- src/main/webapp/WEB-INF/tags/ParticipantBasic.tag
- src/main/webapp/WEB-INF/views/BranchPariticipant.jsp
- src/main/webapp/WEB-INF/views/participantMain.jsp
- '등록일(participantRegDate)'을 '초기상담일(participantInItCons)'로 변경
- 참여자 화면(participantMain.jsp, BranchParticipant.jsp) 및 테이블 컬럼 출력 수정
- XML 매핑 파일(Participant-mapping.xml) 내 쿼리 조건 및 컬럼 정의 변경
- 기본 태그(ParticipantBasic.tag) 항목 업데이트
- 새로운 데이터 필터링 로직 추가
- 초기상담일 기반 검색 조건 적용
- 불필요하거나 중복된 코드 정리
> 초기상담일 데이터 처리 로직 수정 및 관련 용어 변경

- src/main/java/com/jobmoa/app/view/management/UserMAnagementController.java
- src/main/webapp/WEB-INF/tags/gnb.tag
- src/main/webapp/WEB-INF/views/BranchUserManagement.jsp
- src/main/webapp/sql/CreateSQL.sql
- [UserManagementController.java] 신규 추가
- 사용자 관리 관련 로그인 및 페이지 연결 컨트롤러 추가
- URL 매핑 및 페이지 반환 로직 정의
- [CreateSQL.sql] 데이터베이스 테이블 수정 및 컬럼 추가
- `J_참여자관리` 테이블: 기본값 및 새로운 컬럼 추가 (ex. 중단종료일, 간접고용서비스 등)
- `J_참여자관리_로그인정보` 테이블: 비밀번호 기본값 변경 및 새로운 실적 관련 컬럼 추가
- `J_참여자관리_지점` 테이블 재정의: 지점 정보에 유형 및 순서 컬럼 추가
- 불필요한 뷰 및 테이블 제거
- [gnb.tag] 네비게이션 UI 업데이트
- 사이드바 및 헤더 색상 변경, 스타일 개선
- 관리자 권한에 따라 보이는 메뉴 아이템 조정
> feat: 사용자 관리 및 데이터베이스 구조 개선

- src/main/resources/mappings/Participant-mapping.xml
- src/main/webapp/WEB-INF/tags/gnb.tag
- src/main/webapp/WEB-INF/views/DashBoardBranchScoreAndSituation.jsp
- src/main/webapp/WEB-INF/views/NewParticipantsPage.jsp
- src/main/webapp/WEB-INF/views/UpdateCounselPage.jsp
- src/main/webapp/WEB-INF/views/UpdateParticipantsPage.jsp
[participant-management]
- 전담자 변경 쿼리 추가: 전담자_변경일 컬럼 업데이트 추가
- Participant-mapping.xml: 전담자 변경 시 '전담자_변경일' 업데이트 추가
- TODO 주석: 추후 추가 사항 명시
- JSP 파일 텍스트 수정:
- Alert 메시지 텍스트 변경: "진행종료일" -> "중단종료일"
- 진행 단계와 관련된 Alert 메시지 조정
- DashBoard UI 개선:
- 1년 미만 근로자 필터 라벨과 버튼 스타일 수정
- 텍스트 크기와 설명 추가
- GNB 스타일 변경:
- 사이드바 배경 투명도 조정: 44% -> 65%
```
> 전체적인 내용 수정전 마지막 push

- src/main/java/com/jobmoa/app/biz/dashboard/DashboardDTO.java
- src/main/java/com/jobmoa/app/biz/participant/ParticipantDTO.java
- src/main/java/com/jobmoa/app/biz/participantCounsel/CounselDTO.java
- src/main/java/com/jobmoa/app/view/dashboard/DashboardMainController.java
- src/main/java/com/jobmoa/app/view/function/MemberRoleCheck.java
- src/main/java/com/jobmoa/app/view/report/ParticipantAllExcel.java
- src/main/resources/mappings/Counsel-mapping.xml
- src/main/resources/mappings/Dashboard-mapping.xml
- src/main/resources/mappings/Participant-mapping.xml
- src/main/webapp/WEB-INF/tags/ParticipantCounsel.tag
- src/main/webapp/WEB-INF/tags/gnb.tag
- src/main/webapp/WEB-INF/views/DashBoardBranchScoreAndSituation.jsp
- src/main/webapp/WEB-INF/views/DashBoardPage.jsp
- src/main/webapp/WEB-INF/views/DashBoardTotalManagement.jsp
- src/main/webapp/WEB-INF/views/NewParticipantsPage.jsp
- src/main/webapp/WEB-INF/views/UpdateCounselPage.jsp
- src/main/webapp/WEB-INF/views/UpdateParticipantsPage.jsp
- src/main/webapp/js/ApexChartMainDashBoardJS.js
* 특정 필드에 CONVERT(date)를 사용하여 날짜 변환 처리
* 중단종료일(counselEndDate) 제거 및 논리 수정
- Dashboard-mapping.xml 리팩토링
* 기존 대시보드 조회 쿼리 주석 처리 및 신규 KPI 기반 쿼리 추가
* ApexChart 연동을 위한 스크립트(ApexChartMainDashBoardJS.js) 추가
- MemberRoleCheck.java: ENUM에 새로운 역할(GENERAL) 추가 및 기존 역할 이름 변경(본부장)
- Participant-mapping.xml 및 관련 로직 수정
* 중단종료일 필드 제거 및 기간만료일(counselEXPDate) 사용
* UpdateParticipantsPage, NewParticipantsPage 화면에서 유효성 검사 수정
- ParticipantAllExcel.java: 중단종료일 관련 로직 삭제
- DashBoardPage.jsp
* 기존 그래프 라이브러리에서 ApexChart로 전환
* 관련 스크립트 등록 및 스타일 수정
- 필요 없는 코드 및 정의되지 않은 참조 제거로 코드 정리 및 유지보수성 강화
> - Counsel-mapping.xml 파일 내 날짜 변환 기능 추가

- src/main/java/com/jobmoa/app/biz/dashboard/DashboardDTO.java
- src/main/java/com/jobmoa/app/view/dashboard/DashboardMainController.java
- src/main/resources/mappings/Dashboard-mapping.xml
- src/main/webapp/WEB-INF/views/DashBoardPage.jsp
- src/main/webapp/WEB-INF/views/participantMain.jsp
- src/main/webapp/js/ApexChartMainDashBoardJS.js
- `ApexChartMainDashBoardJS.js`:
- 도넛 차트 함수(`apexChartDoughnut`)에 `isBuble` 파라미터 추가로 퍼센트 표기 지원.
- 시리즈 데이터 유효성 검사 로직 추가로 데이터 정합성 강화.
- `checkNegative` 함수 추가로 음수 값 처리.
- 도넛 차트 옵션 개선 및 텍스트 포맷팅 조정.
- `Dashboard-mapping.xml`:
- 중위 70% 데이터 평균값 쿼리 추가(취업률, 알선취업률, 조기취업률, 나은일자리률).
- `DashboardMainController.java`:
- "내 KPI 현황"을 "내 실적 현황"으로 변경.
- 중위 70% 데이터 처리 로직 추가.
- `DashboardDTO.java`:
- 중위 70% 평균값 변수(취업률, 알선취업률, 조기취업률, 나은일자리률) 추가.
- `DashBoardPage.jsp`:
- 차트 렌더링 로직 수정 및 중위 70% 평균값 활용.
- 미사용 인센티브 데이터 차트 관련 코드 주석 처리.
- `participantMain.jsp`:
- `IAP 후` 관련 UI 조건문 수정 및 코드 복원.
-> 전반적인 대시보드 기능 개선, 데이터 정합성 강화, UI 및 UX 개선 반영.
> [대시보드 개선 및 코드 리팩토링]

- src/main/java/com/jobmoa/app/biz/dashboard/DashboardDTO.java
- src/main/java/com/jobmoa/app/view/ajaxPackage/DashboardAjaxController.java
- src/main/java/com/jobmoa/app/view/dashboard/DashboardMainController.java
- src/main/resources/mappings/Dashboard-mapping.xml
- src/main/webapp/WEB-INF/views/DashBoardBranchScoreAndSituation.jsp
- src/main/webapp/WEB-INF/views/DashBoardPage.jsp
- SQL 쿼리 리팩토링:
- 기존 복잡한 WITH 절을 통합하여 근속기간 구분, 순위 및 통계를 효율적으로 계산하도록 변경.
- RANK, PERCENT_RANK, NTILE 함수 도입으로 성능 최적화.
- 근속기간별 등급 경계 점수 및 퍼센타일 계산 추가.
- 대시보드 데이터 변경:
- 전체 최고 점수(totalTopScore), 다음 등급까지 필요한 점수(pointsToNextGrade), 다음 등급(nextGrade) 정보를 계산 및 DTO에 추가.
- Controller 변경:
- DashboardDTO에 totalTopScore, pointsToNextGrade, nextGrade 필드 추가.
- Ajax 응답에 새 필드 값 포함되도록 변경.
- View 수정:
- JSP에서 콘솔 로그 제거.
- 화면에 "다음 등급" 및 필요한 점수를 직관적으로 출력하도록 변경.
- 관리자 권한 여부(isManagement, isBranchManagement) JSP 변수 추가.
- 불필요 코드 정리:
- JSP 및 JavaScript에서 사용하지 않는 함수 및 로그 제거.
- 기존 등급 계산 방식 폐기 후 간소화된 계산 방식으로 대체.
> [대시보드 리팩토링 및 기능 추가]

- pom.xml
- src/main/java/com/jobmoa/app/view/dashboard/DashboardMainController.java
- src/main/java/com/jobmoa/app/view/function/ChangeJson.java
- src/main/resources/mappings/Dashboard-mapping.xml
주요 변경사항:
- `ChangeJson` 클래스:
- `@Controller`에서 `@Component`로 변경하여 유틸리티 용도로 리팩토링.
- `ObjectMapper` 주입 및 JSON 처리 관련 유틸 메서드 추가 (`toJson`, `arrayToJson`, `mapToJson`).
- JSON 배열 변환 메서드 로직 개선 (성능 최적화 및 가독성 향상).
- XML 쿼리:
- 대시보드 쿼리 최적화:
- 통계 및 순위 계산 로직 개선 (중복 제거 및 NTILE 사용).
- 등급 산정 및 다음 등급 계산 방식 최적화.
- 근속기간 구분 로직 간소화.
- `DashboardMainController`:
- DTO 설정 및 데이터 처리 로직 추출 (가독성 및 재사용성 향상).
- 세션 및 쿼리 결과 처리 개선.
- 대시보드 데이터 처리 시 ChangeJson 활용.
- 상수 및 변수명 명확화 (문자열 배열 및 날짜 등).
- pom.xml:
- 사용하지 않는 `jackson-databind` 의존성 제거.
> 기능 개선: ChangeJson 유틸 클래스로 변경 및 JSON 처리 메서드 추가

- src/main/java/com/jobmoa/app/biz/participant/ParticipantDTO.java
- src/main/java/com/jobmoa/app/biz/report/ReportDTO.java
- src/main/java/com/jobmoa/app/view/report/DailyWorkReport3.java
- src/main/java/com/jobmoa/app/view/report/ParticipantAllExcel.java
- src/main/resources/logback.xml
- src/main/resources/mappings/Participant-mapping.xml
- src/main/resources/mappings/Report-mapping.xml
- src/main/resources/sql-map-config.xml
- src/main/webapp/WEB-INF/views/BranchPariticipant.jsp
- src/main/webapp/WEB-INF/views/participantMain.jsp
참여자 및 보고서 관리 기능 개선, 로깅 추가, 엑셀 다운로드 로직 확장
- 참여자 엑셀 다운로드 로직 개선 및 권한별 처리 조건 추가
- 신규 검색 조건 및 필터 로직 추가 (`ParticipantDTO` 및 쿼리 로직 확장)
- 일일보고서 조회 로직 조정 및 데이터 집계 방식 수정
- SQL 매핑 파일 수정 (`where` 조건 동적 처리, 그룹핑 추가)
- 엑셀 다운로드 UI/UX 개선 (로딩 메시지, 오류 처리 개선)
- 로그백 설정 파일 추가 및 통합
> 참여자 및 보고서 관리 기능 개선, 로깅 추가, 엑셀 다운로드 로직 확장
